### ISSUE TITLE
Issue with accountDeletionDate in CurrentUser.yaml

### ISSUE THREAD

**Issue by Rexios80** [vrchatapi/specification#11]
```
accountDeletionDate:
    oneOf:
      - $ref: ./Date.yaml
      - nullable: true
```

I think something is wrong with this piece but I don't know enough about the OpenAPI specification to fix it.

Here are some links I've found regarding this:
https://github.com/Redocly/redoc/issues/1303
https://stackoverflow.com/questions/40920441/how-to-specify-a-property-can-be-null-or-a-reference-with-swagger

I tried doing some of the things in those links but I ended up just making it worse

**Comment by Rexios80** [comment]
Another note on this is I'm pretty sure OpenAPI 3.1 supports this, but I tried upgrading to it and everything broke.

**Comment by Foorack** [comment]
As we are still on 3.0 we have to fix this with the:
```yaml
type: string
nullable: true
```
method. Once we go to 3.1 we need to change this to:
```yaml
oneOf:
  - type: 'null'   # Note the quotes around 'null'
  - type: string
```
or:
```yaml
type:
  - 'null'   # Note the quotes around 'null'
  - string
```
Although 3.1 is currently so incredibly unsupported by everything it will likely be quite a while until that transition happens...
