### ISSUE TITLE
RawFileResponse is empty

### ISSUE THREAD

**Issue by jellejurre** [vrchatapi/specification#460]
https://github.com/vrchatapi/specification/blob/main/openapi/components/responses/files/RawFileResponse.yaml
Do we have a way to return the byte array to the user?

**Comment by VinyarionHyarmendacil** [comment]
After looking into the spec spec, it seems that this should be valid:
```yaml
description: Raw file
content:
  */*:
    schema:
      type: string
      format: binary
```
